### PR TITLE
Initial docs push

### PR DESCRIPTION
**Pull request by foxish**
cc @erikerlandson @tnachen 
@apache-spark-on-k8s/contributors

### CODE REVIEW

**Review by ash211 — COMMENTED** [review]
Are these larger markdown files copies from the current repo?

**Comment by foxish** [comment]
@ash211, running-on-kubernetes.md is a copy with just one minor change at the top. `contribute.md` is new.

**Comment by foxish** [comment]
I'll backport the change in running-on-kubernetes.md to the docs in the main repo; the intent is to have these always in sync. We can setup automation to facilitate that in the future.

**Comment by erikerlandson** [comment]
@foxish I tested it with `xsbt previewSite` and LGTM

**Review by erikerlandson — APPROVED** [review]
In the future, if we want to backport edits, I'd recommend we make actual documentation edits as isolated commits as much as possible, since those are easy to cherrypick or apply as patches.

**Comment by tnachen** [comment]
LGTM!

**Pull request merged**
