### PR TITLE
Added minimum Kubernetes version requirement following PR #528

### PR DESCRIPTION
**Pull request by liyinan926**

### CODE REVIEW

**Comment by foxish** [comment]
LGTM

**Comment by foxish** [comment]
Might also be good to specify kube-dns as a requirement here?
cc/ @kimoonkim

**Comment by liyinan926** [comment]
Good point. kube-dns is required for the headless service for the driver to work.

**Comment by kimoonkim** [comment]
+1

**Comment by liyinan926** [comment]
Done.

**Review by felixcheung — APPROVED** [review]

**Pull request merged**
