### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by erikerlandson**

### CODE REVIEW

**Review by ash211 — APPROVED** [review]

**Comment by foxish** [comment]
Is there a plugin for renaming from .md -> .html automatically?

**Comment by erikerlandson** [comment]
@foxish I'm not aware of one, and my brief attempts at turning one up with google didn't score any hits.

**Comment by foxish** [comment]
Hmm.. The spark documentation does it somehow I think. Worth investigating. Merging this now.

**Comment by erikerlandson** [comment]
I was unable to find any doc on what jenkins plug-ins the spark build assumes.  Actually I'll file an issue for that against their repo

**Pull request merged**
